### ISSUE TITLE
Generate Route non-optimal

### ISSUE THREAD

**Issue by lllama** [felixrieseberg/vsc-ember-cli#10]
Running the generate blueprint command for a route will default to 'resource' not 'route' if you use the following sequence:

> ember generate
> route

Is it possible to have 'route' be the first option?

**Comment by t-sauer** [comment]
VSCode doesn't sort these items based on how strong they match, it just keeps the order of the items the same as in the array which provides these quick pick items. Right now they are sorted alphabetically by name (which makes a lot of sense I guess).

To solve the problem (which should be changed in my opinion, since most people enter `route` when they want to create a route and not a resource), there are two possible solutions: 
1. Only match on the label of the quick pick item. Right now the items are matched by label and by description and the description for `resource` contains the word route.
2. Change the order of the quick pick items and put `route` before `resource`.

I guess the sort order of the items should not be changed since it makes a lot of sense to keep them sorted alphabetically, so I would go for the first option. I expect most people to use the commands like they would use the command line anyway and most descriptions don't really contain a lot of meaningful words that would justify matching.
