### ISSUE TITLE
Serve won't start

### ISSUE THREAD

**Issue by franciscojf** [felixrieseberg/vsc-ember-cli#11]
## It looks like that when y run the serve command it gives me the following error: 

version: 2.4.2

You have to be inside an ember-cli project in order to use the serve command.

Ember ember process exited with code 1

I searched the issue and found out that I need to set the flag VSC_EMBER_CLI_DEBUG in order to see what is happening with my environment. Where do I set this variable? What value am I supposed to set it to?

Thank You

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting! Dumb question - do you have the Ember in the root level of Visual Studio code when you run the command? Because it seems like Ember is being run just fine, it's just complaining about not finding an Ember app ;-)

The `VSC_EMBER_CLI_DEBUG` needs to be an environment variable (set to true), but I assume that in your case, it's just that the wrong folder is open. Could you kindly check that for me?

**Comment by franciscojf** [comment]
Yes I got it working! Apparently I needed to move to the next folder (the one that the plugin created) in order to work. XD

Thanks for the fast response!

**Comment by felixrieseberg** [comment]
Sure, happy you got it working!
