### ISSUE TITLE
Generated workspace files should be added to gitignore

### ISSUE THREAD

**Issue by offirgolan** [felixrieseberg/vsc-ember-cli#24]
Hi there,

First of all, great job on this extension! Its wonderful! One thing that would be a great addition is to add the following to the .gitignore file when you setup the workspace:

```
/typings/*
/.vscode/*
.vscodeignore
jsconfig.json
```

I dont really think they belong in a git repo (at least the typings directory). If you disagree with some of these, maybe have a config option where we can declare the ignored file rule on workspace setup? Just throwing out some ideas 😛

**Comment by t-sauer** [comment]
Pretty much all the entries you listed are nothing specific to this plugin but rather general VSCode stuff (even though the plugin makes use of them). I don't think we should add general VSCode stuff to the gitignore list just because we also use it in the plugin. For example it would be pretty confusing if a user had all these files added to his repository and installs the plugin later and suddenly all the files are not tracked anymore.

**Comment by offirgolan** [comment]
@t-sauer makes sense! Thanks for clarifying 😸
