### ISSUE TITLE
Commands do nothing

### ISSUE THREAD

**Issue by kellyselden** [felixrieseberg/vsc-ember-cli#8]
First time trying this all out. Installed vscode, installed this plugin, then loaded up an addon project I'm working on. The command completion is working, but the commands do nothing. I tried Ember Test and generating a helper. ember test caused the output window to open, but nothing happened. the generate, just nothing happened. gave it a few minutes. Would love to help you figure it out.

I'm on Windows 7 x64.

**Comment by kellyselden** [comment]
Doesn't work for me on my Win 10 x64 machine either.

**Comment by felixrieseberg** [comment]
Hey Kelly, thanks for letting me know! This is super interesting to me, because people have told me about their issues, but I could never reproduce it with my machines. I think the first step is that I make the easier to diagnose what's wrong - then, I'd _really_ appreciate it if you could give it a try again, just so that we see what's wrong.

All the integration is doing is to spawn/exec "ember" commands using powershell.exe, so I find it confusion that it'd ever not work. Any ideas?

**Comment by kellyselden** [comment]
No ideas. Should there be something to search for in task manager or something? I don't see anything to indicate something is running, no powershell or node. I'll help anyway I can, via screen cap or pairing or whatever.

**Comment by felixrieseberg** [comment]
Hey! Pairing would also be _amazing_, but I won't be back home for a few days - however, I just pushed out a small patch that will always open up the output window if the environment variable `VSC_EMBER_CLI_DEBUG` is set.

Would you mind updating the addon, setting the variable, and trying some commands? I'd love to see what's happening on the PowerShell level. Thanks so much in advance!

**Comment by felixrieseberg** [comment]
(Also, for reference, this seems to be the same as #1)

**Comment by kellyselden** [comment]
closing as duplicate
